"""
Django settings for reasup project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--y_*s9dme-(y2*fa3e8f@t7+%_%f83%yjda+dpshrq+b487*e1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tickets.apps.TicketsConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reasup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reasup.wsgi.application'


# Подключение базы данных
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'reasup_db',  # Название базы данных
        'USER': 'postgres',   # Имя пользователя базы данных
        'PASSWORD': '1323',  # Ваш пароль
        'HOST': 'localhost',  # Хост базы данных
        'PORT': '5432',       # Порт (по умолчанию для PostgreSQL)
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py

STATIC_URL = '/static/'  # Указывает на URL, по которому будут доступны статические файлы

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Убедитесь, что эта директория существует
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MEDIA настройки (если у вас есть медиафайлы, такие как изображения)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Настройка телеграм-бота
TELEGRAM_BOT_TOKEN = '7612483510:AAGzVgcvy9gzLaLxjuv02-2-VE5s8pZtdCM'
TELEGRAM_CHAT_ID = '442468143'
TELEGRAM_NEW_TICKETS_CHAT_ID = '442468143'  # новый чат для уведомлений о новых заявках

# Отправлять письма через SMTP-сервер
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'            # адрес SMTP-сервера
EMAIL_PORT = 465                          # порт (обычно 587 для TLS)
EMAIL_HOST_USER = 'reasupinfo@yandex.ru'         # учётная запись
EMAIL_HOST_PASSWORD = 'lpdeydrtorzhrbhe'   # пароль
EMAIL_USE_TLS = False                      # выключить TLS-шифрование
EMAIL_USE_SSL = True                # включаем SSL

# Адрес, от имени которого будут приходить письма
DEFAULT_FROM_EMAIL = 'reasupinfo@yandex.ru'

